# golangci-lint configuration file
# See https://golangci-lint.run/usage/configuration/ for all options
version: 2

linters:
  settings:
    revive:
      rules:
       - name: unused-parameter
         arguments: 
           - allow-regex: "(cmd|args|_args|_cmd|pkg|outputFn|)"
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - revive
    - gocritic
    - misspell
    - dupl
    - gocyclo
    - nakedret
    - unconvert
    - unparam
    - whitespace

formatters:

output:
  format: colored-line-number
  print-issued-lines: true

run: 
  timeout: 3m
# You can add custom excludes or configure per-linter options below
