# GoReleaser configuration file for voltig-cli
# See https://goreleaser.com/customization/ for more options
version: 2
project_name: voltig

dist: dist

builds:
  - main: ./main.go
    binary: voltig
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w
        -X 'voltig/cmd.version={{.Version}}'
        -X 'voltig/cmd.commit={{.ShortCommit}}'
        -X 'voltig/cmd.date={{.Date}}'"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: voltigdev
    name: voltig

changelog:
  sort: desc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: voltig
    commit_author:
      name: Voltig
      email: voltig@voltig.dev
    commit_msg_template: "chore: update to {{ .Version }}"
    directory: homebrew-tap
    description: "Voltig CLI - Cross-platform package manager and dev environment tool."
    install: |
      bin.install "voltig"
    caveats: |
      To get started, run:
        voltig --help
    test: |
      voltig --version
    repository:
      owner: voltigdev
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
